spring:
  application:
    name: Navigator
  datasource:
    url: jdbc:h2:file:./data/db/navdb
    hikari:
      driver-class-name: org.h2.Driver
      username: sa
      password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
  profiles:
    active: prod
server:
  port: 8000
