name: Build and Push Docker Image on Release Branch

on:
  push:
    branches:
      - release
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with all history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all history is fetched to get tags

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine tag
        id: tag
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            # 获取最近的标签，如果没有标签则使用 latest
            LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "latest")
            echo "TAG=${LATEST_TAG}" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/navigator:latest
            ${{ secrets.DOCKER_USERNAME }}/navigator:${{ env.TAG }}
